sudo: false

language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
  - 2.12.0-M3
env:
  - SBT_MODULE=core
  - SBT_MODULE=config
  - SBT_MODULE=play24
  - SBT_MODULE=play25

matrix:
  exclude:
    - scala: 2.12.0-M3
      env: SBT_MODULE=play24
    - scala: 2.12.0-M3
      env: SBT_MODULE=play25

script:
  - sbt ++$TRAVIS_SCALA_VERSION $SBT_MODULE/test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
