addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.3")
addSbtPlugin("com.github.scalaprops" % "sbt-scalaprops" % "0.1.1")
addSbtPlugin("com.eed3si9n" % "sbt-doge" % "0.1.5")
